name: Download, Split, and Upload to Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        run: |
          curl -L "http://gs2.ww.prod.dl.playstation.net/gs2/appkgo/prod/CUSA00900_00/2/f_2df8e321f37e2f5ea3930f6af4e9571144916013ee38893d881890b454b5fed6/f/UP9000-CUSA00900_00-BLOODBORNE000000_0.pkg" --output "./UP9000-CUSA00900_00-BLOODBORNE000000_0.pkg"

      - name: Split File into 2GB parts
        run: |
          split -b 2G ./UP9000-CUSA00900_00-BLOODBORNE000000_0.pkg "UP9000-CUSA00900_00-BLOODBORNE000000_0.pkg.part"

      - name: Create Release and Upload Parts
        uses: softprops/action-gh-release@v2
        with:
          name: "Bloodborne Update PKG (4GB Split)"
          tag_name: "v1.0-split"
          files: |
            ./original.pkg.part*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
